version: "3"
services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    environment:
      - SERVER_URL=http://server:80/hola.html
    depends_on:
      - server
    volumes:
      - my_volume:/app
    networks:
      - sample_network
  server:
    image: nginx:1.19.0
    ports:
      - "8085:80"
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - sample_network

networks:
  sample_network:
    driver: bridge
volumes:
  my_volume:
    driver: local